import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export function proxy(request: NextRequest) {
  if (request.nextUrl.pathname === "/") {
    const url = request.nextUrl.clone();
    // OGP/Twitter metadata is generated by Next's layout metadata.
    // Rewriting to a static HTML file bypasses <head> generation.
    url.pathname = "/oekaki";
    return NextResponse.rewrite(url);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/"],
};
